version: '3'

services:
  inge-4:
    build:
      context: '${INGE4_PATH:-.}'
      dockerfile: Dockerfile
      args:
        - PORT=8000
    container_name: inge-4
    environment:
      - PORT=8000
      - REDIS_HOST=redis
    ports:
      - 8554:8000
  redis:
    image: "redis:alpine"
