version: '3'

services:
  inge-4:
    build:
      context: '.'
      dockerfile: Dockerfile
      args:
        - PORT=8000
    container_name: inge-4
    environment:
      - PORT=8000
    ports:
      - 8000:8000
    volumes:
      - '.:/app'
