name: Rebuild python virtual env

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v4

      - name: prep
        run: sudo mkdir -p /var/www/html
      - name: prep chown
        run: sudo chown `id -u`:`id -g` /var/www/html

      - name: copy project to run location.
        run: cp -r * /var/www/html

      - name: Create env
        run: python3.8 -m venv /var/www/html/.venv

      - name: Install requirements
        run: cd /var/www/html; source .venv/bin/activate; pip install --upgrade pip; pip install --requirement requirements.txt

      - name: Create archive
        run: cd /var/www/html; tar -czf /home/runner/work/inge-4/inge-4/inge4_venv_${{ env.RELEASE_VERSION }}.tar.gz .venv

      - name: Upload venv tar
        uses: actions/upload-artifact@v4
        with:
          name: inge4_venv_${{ env.RELEASE_VERSION }}
          path: inge4_venv_${{ env.RELEASE_VERSION }}.tar.gz
