name: Create release package

on:
  create:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
            python-version: 3.8
      - name: Install dependencies
        run: |
            python3.8 -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip3.8 install -r requirements.txt; fi
      - name: Create version.json
        run: 'echo "{ \"version\": \"${{ env.RELEASE_VERSION }}\", \"git_ref\": \"$GITHUB_SHA\"}" > inge4/version.json'
        shell: bash
      - name: Create tar
        run: tar -czf inge4_${{ env.RELEASE_VERSION }}.tar.gz .
      - name: Upload release tar
        uses: actions/upload-artifact@v1
        with:
          name: inge4_${{ env.RELEASE_VERSION }}
          path: inge4_${{ env.RELEASE_VERSION }}.tar.gz
