name: Python application

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-20.04
    continue-on-error: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: make venv
      - name: Check linting
        run: make check
      - name: Test
        run: make test
      - name: Audit
        run: make audit
