name: Python application

on: [ push, pull_request ]

jobs:
  build:
    env:
      USE_PYTEST_REDIS: False

    runs-on: ubuntu-20.04
    continue-on-error: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: make venv
      - name: Check linting
        run: make check
      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: 6
      - name: Test
        run: make test
      - name: Audit
        run: make audit
      - name: Lint
        run: make lint
      - name: check-types
        run: make check-types
